name: test_build_deploy
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.1

    steps:
      - uses: actions/checkout@v3

      - name: Yarn install
        uses: ./.github/actions/test_build_deploy

      - name: Test
        run: yarn test

  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.1
    if: github.ref_name == 'master' || github.ref_name == 'staging' || github.ref_name == 'develop'
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Yarn install
        uses: ./.github/actions/test_build_deploy

      - name: delete SEO files
        if: github.ref_name != 'master'
        run: |
          rm -f ./static/robots.txt ./static/sitemap.xml && \
          echo "User-agent: *\nDisallow: /\n" > ./static/robots.txt

      - name: Yarn Generate
        run: yarn generate
        env:
          ANALYTICS_ID: ${{ secrets.ANALYTICS_ID }}
          BASE_URL: ${{ github.ref_name == 'master' && secrets.PROD_BASE_URL || github.ref_name == 'staging' && secrets.STG_BASE_URL || secrets.DEV_BASE_URL }}
          PAYJP_PUBLIC_KEY: ${{ secrets.PAYJP_PUBLIC_KEY }}

      - name: Upload Directory
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master' || github.ref_name == 'staging'
    needs: build
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist-dir
      - name: Deploy to XSERVER
        run: |
          echo "${{ secrets.XSERVER_PRIVATE_KEY }}" > x-server.key
          chmod 600 x-server.key
          rsync -avz --delete --delete-delay --delay-updates -e "ssh -o StrictHostKeyChecking=no -i x-server.key -p 10022" ./dist-dir/ ${{ secrets.XSERVER_USER }}@${{ secrets.XSERVER_HOST }}:${{ secrets.STAGING_DIRECTORY }}
