name: test_build_deploy
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.1

    steps:
      - uses: actions/checkout@v3

      - name: Yarn install
        uses: ./.github/actions/test_build_deploy

      - name: Test
        run: yarn test

  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.1
    if: github.ref_name == 'master' || github.ref_name == 'staging' || github.ref_name == 'develop'
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Yarn install
        uses: ./.github/actions/test_build_deploy

      - name: delete SEO files
        if: github.ref_name != 'master'
        run: |
          rm -f ./static/robots.txt ./static/sitemap.xml && \
          "echo 'User-agent: *\nDisallow: /\n' > ./static/robots.txt"

      - name: Yarn Generate
        run: yarn generate

      - name: Upload Directory
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master' || github.ref_name == 'staging' || github.ref_name == 'develop'
    needs: build
    steps:
      - run: ls -la
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: dist
      - run: ls -la
  #     - name: Deploy
  #       env:
  #         DEPLOY_DIRECTORY: ${{ github.ref_name == 'master' && secrets.PRODUCTION_DIRECTORY || github.ref_name == 'staging' && secrets.STAGING_DIRECTORY || secrets.DEVELOPMENT_DIRECTORY }}
  #       run: |
  #         echo "${{ secrets.XSERVER_PRIVATE_KEY }}" > x-server.key && chmod 600 x-server.key && \
  #         ssh -o StrictHostKeyChecking=no -i x-server.key ${{ secrets.XSERVER_USER }}@${{ secrets.XSERVER_HOST }} -l ${{ secrets.XSERVER_USER }} -p 10022 \
  #         "cd $DEPLOY_DIRECTORY && git pull origin ${{ github.ref_name }} && composer install --optimize-autoloader --no-dev && \
  #         php artisan config:cache && php artisan route:cache && php artisan migrate --force && exit"
